meuprimeiroprojeto/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#home'
  resources :turmas
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

meuprimeiroprojeto/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

meuprimeiroprojeto/app/models/turma.rb
class Turma < ApplicationRecord
end

meuprimeiroprojeto/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

meuprimeiroprojeto/app/models/usuario.rb
class Usuario < ApplicationRecord
    
end

meuprimeiroprojeto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

meuprimeiroprojeto/app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :authenticate_user!
    def home 
        #####
    end 
end

meuprimeiroprojeto/app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turma_params
      params.require(:turma).permit(:nome_turma, :dias_da_semana, :horario_inicio, :horario_termino, :carga_horaria_minima, :carga_horaria_maxima, :capacidade)
    end
end

meuprimeiroprojeto/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome_usuario, :matricula_usuario, :tipo_usuario, :email_usuario, :senha_usuario)
    end
end

meuprimeiroprojeto/app/helpers/application_helper.rb
module ApplicationHelper
end

meuprimeiroprojeto/app/helpers/home_helper.rb
module HomeHelper
end

meuprimeiroprojeto/app/helpers/turmas_helper.rb
module TurmasHelper
end

meuprimeiroprojeto/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

meuprimeiroprojeto/app/views/home/home.html.erb
<h1> Minha Home Page </h1>

meuprimeiroprojeto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meuprimeiroprojeto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
 
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

meuprimeiroprojeto/app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_turma %>
    <%= form.text_field :nome_turma %>
  </div>

  <div class="field">
    <%= form.label :dias_da_semana %>
    <%= form.text_field :dias_da_semana %>
  </div>

  <div class="field">
    <%= form.label :horario_inicio %>
    <%= form.time_select :horario_inicio %>
  </div>

  <div class="field">
    <%= form.label :horario_termino %>
    <%= form.time_select :horario_termino %>
  </div>

  <div class="field">
    <%= form.label :carga_horaria_minima %>
    <%= form.number_field :carga_horaria_minima %>
  </div>

  <div class="field">
    <%= form.label :carga_horaria_maxima %>
    <%= form.number_field :carga_horaria_maxima %>
  </div>

  <div class="field">
    <%= form.label :capacidade %>
    <%= form.number_field :capacidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

meuprimeiroprojeto/app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

meuprimeiroprojeto/app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Nome turma</th>
      <th>Dias da semana</th>
      <th>Horario inicio</th>
      <th>Horario termino</th>
      <th>Carga horaria minima</th>
      <th>Carga horaria maxima</th>
      <th>Capacidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.nome_turma %></td>
        <td><%= turma.dias_da_semana %></td>
        <td><%= turma.horario_inicio %></td>
        <td><%= turma.horario_termino %></td>
        <td><%= turma.carga_horaria_minima %></td>
        <td><%= turma.carga_horaria_maxima %></td>
        <td><%= turma.capacidade %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

meuprimeiroprojeto/app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

meuprimeiroprojeto/app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome turma:</strong>
  <%= @turma.nome_turma %>
</p>

<p>
  <strong>Dias da semana:</strong>
  <%= @turma.dias_da_semana %>
</p>

<p>
  <strong>Horario inicio:</strong>
  <%= @turma.horario_inicio %>
</p>

<p>
  <strong>Horario termino:</strong>
  <%= @turma.horario_termino %>
</p>

<p>
  <strong>Carga horaria minima:</strong>
  <%= @turma.carga_horaria_minima %>
</p>

<p>
  <strong>Carga horaria maxima:</strong>
  <%= @turma.carga_horaria_maxima %>
</p>

<p>
  <strong>Capacidade:</strong>
  <%= @turma.capacidade %>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>

meuprimeiroprojeto/app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_usuario %>
    <%= form.text_field :nome_usuario %>
  </div>

  <div class="field">
    <%= form.label :matricula_usuario %>
    <%= form.text_field :matricula_usuario %>
  </div>

  <div class="field">
    <%= form.label :tipo_usuario %>
    <%= form.text_field :tipo_usuario %>
  </div>

  <div class="field">
    <%= form.label :email_usuario %>
    <%= form.text_field :email_usuario %>
  </div>

  <div class="field">
    <%= form.label :senha_usuario %>
    <%= form.text_field :senha_usuario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

meuprimeiroprojeto/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

meuprimeiroprojeto/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadastro de Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matrícula </th>
      <th>Tipo</th>
      <th>E-mail</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome_usuario %></td>
        <td><%= usuario.matricula_usuario %></td>
        <td><%= usuario.tipo_usuario %></td>
        <td><%= usuario.email_usuario %></td>
        <td><%= usuario.senha_usuario %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

meuprimeiroprojeto/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

meuprimeiroprojeto/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome usuario:</strong>
  <%= @usuario.nome_usuario %>
</p>

<p>
  <strong>Matricula usuario:</strong>
  <%= @usuario.matricula_usuario %>
</p>

<p>
  <strong>Tipo usuario:</strong>
  <%= @usuario.tipo_usuario %>
</p>

<p>
  <strong>Email usuario:</strong>
  <%= @usuario.email_usuario %>
</p>

<p>
  <strong>Senha usuario:</strong>
  <%= @usuario.senha_usuario %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>